Repository Dubutoto/StockRadar, pull requests merged in 2025-03, with the labels that each got.

#46 feat: 고객문의 작성 4차 구현 완료(#43)
  src/main/java/org/example/stockradar/feature/CustomerInquiry/controller/CustomerInquiryController.java
  src/main/java/org/example/stockradar/feature/CustomerInquiry/dto/CustomerInquiryResponseDto.java
  src/main/java/org/example/stockradar/feature/CustomerInquiry/dto/CustomerInquiryUserRequestDto.java
  src/main/java/org/example/stockradar/feature/CustomerInquiry/service/CustomerInquiryService.java
  src/main/java/org/example/stockradar/feature/customerInquiryprocessing/dto/CustomerInquiryProcessingRequestDto.java
  src/main/resources/static/js/customerInquiry/customerInquiry.js
  src/main/resources/templates/customerInquiry/customerInquiry.html
  src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryControllerTwoTest.java
Labels: feature

#48 feat: 회원가입시 휴대폰 인증 구현 완료(#40)
  .gitignore
  build.gradle
  src/main/java/org/example/stockradar/StockradarApplication.java
  src/main/java/org/example/stockradar/config/SecurityConfig.java
  src/main/java/org/example/stockradar/feature/auth/controller/AuthController.java
  src/main/java/org/example/stockradar/feature/auth/controller/ViewController.java
  src/main/java/org/example/stockradar/feature/auth/service/CoolsmsService.java
  src/main/resources/templates/auth/idInquiry.html
  src/main/resources/templates/auth/signIn.html
  src/main/resources/templates/auth/signUp.html
Labels: feature, security, ui

#66 feat: 레이아웃 링크 수정, 마이페이지 구현완료(#62)
  build.gradle
  logs/app.log
  src/main/java/org/example/stockradar/feature/auth/controller/AuthController.java
  src/main/java/org/example/stockradar/feature/auth/controller/ProfileController.java
  src/main/resources/application-local.yml
  src/main/resources/templates/auth/profile.html
  src/main/resources/templates/layout.html
Labels: feature, ui, chore

#73 feat: 권한별 layout수정 (#69)
  src/main/java/org/example/stockradar/config/SecurityConfig.java
  src/main/java/org/example/stockradar/feature/auth/controller/ViewController.java
  src/main/java/org/example/stockradar/feature/auth/dto/ViewResponseDto.java
  src/main/java/org/example/stockradar/feature/auth/service/CustomUserDetailsService.java
  src/main/java/org/example/stockradar/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/static/assets/js/customerInquiry/customerInquiry.js
  src/main/resources/static/assets/js/mainView/mainView.js
  src/main/resources/templates/customerInquiry/customerInquiry.html
  src/main/resources/templates/layout.html
  src/test/java/org/example/stockradar/view/CustomUserDetailsServiceTest.java
Labels: feature

#81 chore: 시큐리티 설정 및 layout 변경 세팅 완료 (#80)
  src/main/java/org/example/stockradar/config/SecurityConfig.java
  src/main/java/org/example/stockradar/feature/product/controller/ProductCategoryController.java
  src/main/resources/templates/layout.html
Labels: chore

#86 bugfix: 맵핑 에러 해결& 테스트 까지 완료
  src/main/java/org/example/stockradar/feature/auth/controller/AuthController.java
  src/main/java/org/example/stockradar/feature/auth/controller/ViewController.java
  src/main/resources/application-local.yml
Labels: bug, done

#87 feat: 상품엔터티 수정완료(#83)
  src/main/java/org/example/stockradar/feature/crawl/CrawlDataInitializer.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Category.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Price.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Product.java
  src/main/java/org/example/stockradar/feature/crawl/entity/StockStatus.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Store.java
  src/main/java/org/example/stockradar/feature/crawl/entity/StoreStock.java
  src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
  src/main/java/org/example/stockradar/feature/crawl/repository/StoreStockRepository.java
Labels: feature

#90 Feature/78
  .github/ISSUE_TEMPLATE/daily-report-.md
  build.gradle
  src/main/java/org/example/stockradar/feature/alert/controller/ViewController.java
  src/main/java/org/example/stockradar/feature/alert/repository/AlertRepository.java
  src/main/java/org/example/stockradar/feature/alert/service/alertService.java
  src/main/java/org/example/stockradar/feature/board/controller/BoardController.java
  src/main/java/org/example/stockradar/feature/board/dto/BoardRequestDto.java
  src/main/java/org/example/stockradar/feature/board/dto/BoardResponseDto.java
  src/main/java/org/example/stockradar/feature/board/repository/BoardContentRepository.java
  src/main/java/org/example/stockradar/feature/board/repository/BoardRepository.java
  src/main/java/org/example/stockradar/feature/board/service/BoardService.java
  src/main/java/org/example/stockradar/feature/notification/controller/ViewController.java
  src/main/java/org/example/stockradar/feature/notification/dto/NotificationRequestDto.java
  src/main/java/org/example/stockradar/feature/notification/dto/NotificationResponseDto.java
  src/main/java/org/example/stockradar/feature/notification/entity/MemberNotification.java
  src/main/java/org/example/stockradar/feature/notification/entity/Notification.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationLog.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationSetting.java
  src/main/java/org/example/stockradar/feature/notification/repository/NotificationRepository.java
  src/main/java/org/example/stockradar/feature/notification/service/NotificationService.java
  src/main/resources/templates/auth/accountDetails.html
  src/main/resources/templates/board/boardForm.html
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/form.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/write.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/notification/wishlist.html
Labels: feature, ui, chore

#92 feat:1차 스케줄러 구현 완료 (#88)
  src/main/java/org/example/stockradar/feature/crawl/entity/Product.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Store.java
  src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/crawl/service/ProductStockService.java
  src/main/java/org/example/stockradar/feature/product/controller/ProductCategoryController.java
  src/main/java/org/example/stockradar/global/exception/ErrorCode.java
  src/main/java/org/example/stockradar/global/exception/specific/CrawlException.java
  src/main/resources/templates/product/gpu/rtx3050.html
Labels: feature

#94 feat: rtx3050 조회 1차 구현(#93)
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/crawl/service/ProductStockService.java
  src/main/java/org/example/stockradar/feature/product/controller/ProductCategoryController.java
  src/main/java/org/example/stockradar/feature/product/dto/ProductResponseDto.java
  src/main/java/org/example/stockradar/feature/product/rtx3050/controller/Rtx3050Controller.java
  src/main/java/org/example/stockradar/feature/product/rtx3050/repository/Rtx3050Repository.java
  src/main/java/org/example/stockradar/feature/product/rtx3050/service/Rtx3050Service.java
  src/main/java/org/example/stockradar/global/exception/ErrorCode.java
  src/main/java/org/example/stockradar/global/exception/specific/ProductException.java
  src/main/resources/static/assets/js/product/rxt3050.js
  src/main/resources/templates/product/gpu/rtx3050.html
Labels: feature

#97 test: rtx3050 조회 예외처리 테스트 완료(#95)
  src/test/java/org/example/stockradar/product/rxt3050/Rtx3050ControllerExceptionTest.java
Labels: test

#99 feat: 크롤링용 엔티티 수정, 크롤링 파이썬 서버 업로드
  crawlingServer/__pycache__/crawler.cpython-313.pyc
  crawlingServer/__pycache__/url_config.cpython-313.pyc
  crawlingServer/crawler.py
  crawlingServer/main.py
  crawlingServer/requirements.txt
  crawlingServer/url_config.py
  src/main/java/org/example/stockradar/feature/auth/jwt/JwtTokenProvider.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Category.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Price.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Product.java
  src/main/java/org/example/stockradar/feature/crawl/entity/StockStatus.java
  src/main/java/org/example/stockradar/feature/crawl/entity/Store.java
  src/main/resources/application-local.yml
Labels: feature, merge ready

#109 refactor : rex3050 시나리오3 구현 완료 (#106)
  src/main/java/org/example/stockradar/feature/crawl/entity/Product.java
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/product/dto/ProductResponseDto.java
  src/main/java/org/example/stockradar/feature/product/rtx3050/controller/Rtx3050Controller.java
  src/main/java/org/example/stockradar/feature/product/service/ProductALLServiceWithCache.java
Labels: refactor

#111 Feature/91
  .github/ISSUE_TEMPLATE/bug_report.md
  build.gradle
  src/main/java/org/example/stockradar/feature/auth/entity/Member.java
  src/main/java/org/example/stockradar/feature/board/controller/BoardController.java
  src/main/java/org/example/stockradar/feature/board/dto/BoardDeleteRequestDto.java
  src/main/java/org/example/stockradar/feature/board/dto/BoardRequestDto.java
  src/main/java/org/example/stockradar/feature/board/dto/BoardResponseDto.java
  src/main/java/org/example/stockradar/feature/board/entity/Board.java
  src/main/java/org/example/stockradar/feature/board/entity/BoardContent.java
  src/main/java/org/example/stockradar/feature/board/entity/Comments.java
  src/main/java/org/example/stockradar/feature/board/entity/NestedComments.java
  src/main/java/org/example/stockradar/feature/board/repository/BoardContentRepository.java
  src/main/java/org/example/stockradar/feature/board/repository/BoardRepository.java
  src/main/java/org/example/stockradar/feature/board/service/BoardService.java
  src/main/java/org/example/stockradar/feature/notification/dto/NotificationRequestDto.java
  src/main/java/org/example/stockradar/feature/notification/dto/NotificationResponseDto.java
  src/main/java/org/example/stockradar/feature/notification/entity/MemberNotification.java
  src/main/java/org/example/stockradar/feature/notification/entity/Notification.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationLog.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationSetting.java
  src/main/resources/static/assets/css/demo/demo4/demo4.css
  src/main/resources/static/assets/css/style.css
  src/main/resources/static/assets/sass/style.scss
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/form.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/write.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/notification/wishlist.html
  src/test/java/org/example/stockradar/boardTest/BoardServiceTest.java
Labels: docs, feature, refactor, ui, approved, test

#120 feat: 3060Ti,4060Ti 페이지 구현 완료(#119)
  crawlingServer/__pycache__/crawler.cpython-313.pyc
  crawlingServer/__pycache__/url_config.cpython-313.pyc
  src/main/java/org/example/stockradar/feature/crawl/service/ProductStockService.java
  src/main/java/org/example/stockradar/feature/product/rtx3060Ti/controller/Rtx3060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/resources/static/assets/js/product/rxt3060Ti.js
  src/main/resources/static/assets/js/product/rxt4060Ti.js
  src/main/resources/templates/product/gpu/rtx3060Ti.html
  src/main/resources/templates/product/gpu/rtx4060Ti.html
Labels: feature

#122 feat: 3060,4060Ti 시나리오2번 구현 완료(#121)
  src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
  src/main/java/org/example/stockradar/feature/crawl/service/ProductStockService.java
  src/main/java/org/example/stockradar/feature/product/rtx3060Ti/controller/Rtx3060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
Labels: feature

#125 Feature/110
  src/main/java/org/example/stockradar/config/SecurityConfig.java
  src/main/java/org/example/stockradar/feature/auth/repository/MemberRepository.java
  src/main/java/org/example/stockradar/feature/board/controller/BoardController.java
  src/main/java/org/example/stockradar/feature/board/controller/CommentController.java
  src/main/java/org/example/stockradar/feature/board/dto/CommentDeleteRequestDto.java
  src/main/java/org/example/stockradar/feature/board/dto/CommentRequestDto.java
  src/main/java/org/example/stockradar/feature/board/dto/CommentResponseDto.java
  src/main/java/org/example/stockradar/feature/board/entity/BoardContent.java
  src/main/java/org/example/stockradar/feature/board/entity/Comments.java
  src/main/java/org/example/stockradar/feature/board/repository/BoardRepository.java
  src/main/java/org/example/stockradar/feature/board/repository/CommentRepository.java
  src/main/java/org/example/stockradar/feature/board/service/BoardService.java
  src/main/java/org/example/stockradar/feature/board/service/CommentService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/layout.html
Labels: feature

#133 feat: rtx4060Ti 시나리오 4번 구현완료
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/product/dto/ProductStaticCacheDto.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheService.java
Labels: feature

#135 refactor: 시나리오4번 V2구현완료(#134)
  src/main/java/org/example/stockradar/feature/product/dto/ProductCacheDto.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV2.java
Labels: refactor

#137 bugfix: Redis LocalDateTime 직렬화 버그수정 완료 (#136)
  src/main/java/org/example/stockradar/config/JacksonConfig.java
  src/main/java/org/example/stockradar/config/ProductRedisConfig.java
  src/main/java/org/example/stockradar/feature/product/dto/ProductStaticCacheDto.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV2.java
Labels: bugfix

#143 refactor: 스캐줄러 코드 리펙토링 완료(#142)
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV2.java
Labels: refactor

#144 feat: 파이썬 시스템 로그 추가, 로그파일 자동삭제 로직 추가
  crawlingServer/__pycache__/crawler2.cpython-313.pyc
  crawlingServer/__pycache__/url_config.cpython-313.pyc
  crawlingServer/coroutine.py
  crawlingServer/multiThreads.py
  crawlingServer/requirements.txt
  crawlingServer/singleThread.py
Labels: refactor, maintenance

#147 refactor: 제품 재고 쿼리 튜닝 완료(#146)
  src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
  src/main/java/org/example/stockradar/feature/product/dto/ProductResponseDto.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiLikeService.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiLikeV2Service.java
Labels: refactor

#149 refactor: 스케줄러 변경사항 제품 재고 페이지 쿼리 수정(#148)
  src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3.java
Labels: refactor

#157 refactor: 4060Ti 조회비동기 처리 구현 완료(#155)
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
Labels: refactor

#159 bugfix: 비동기 처리 버그픽스 구현 완료(#158)
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
  src/main/resources/application.yml
Labels: bugfix

#169 feat: redis 고장 처리 구현 완료(#167)
  src/main/java/org/example/stockradar/feature/auth/service/RedisSmtpService.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
  src/main/resources/application-local.yml
  src/main/resources/templates/customerInquiry/customerInquiry.html
Labels: feature

#176 feat: 고객문의 처리 구현 완료(#170)
  src/main/java/org/example/stockradar/config/ProductRedisConfig.java
  src/main/java/org/example/stockradar/feature/CustomerInquiry/dto/CustomerInquiryUserRequestDto.java
  src/main/java/org/example/stockradar/feature/CustomerInquiry/entity/CustomerInquiry.java
  src/main/java/org/example/stockradar/feature/CustomerInquiry/service/CustomerInquiryService.java
  src/main/java/org/example/stockradar/feature/customerInquiryprocessing/controller/CustomerInquiryProcessingController.java
  src/main/java/org/example/stockradar/feature/customerInquiryprocessing/dto/CustomerInquiryProcessingResponseDto.java
  src/main/java/org/example/stockradar/feature/customerInquiryprocessing/service/CustomerInquiryProcessingService.java
  src/main/resources/application.yml
  src/main/resources/static/assets/js/customerInquiryprocessing/customerInquiryDetail.js
  src/main/resources/static/assets/js/customerInquiryprocessing/customerInquiryprocessing.js
  src/main/resources/templates/customerInquiry/customerInquiry.html
  src/main/resources/templates/customerInquiryprocessing/customerInquiryprocessing.html
  src/main/resources/templates/customerInquiryprocessing/detail.html
  src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryControllerTest.java
  src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryControllerTwoTest.java
  src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryServiceTest.java
Labels: feature

#178 refactor:재고 페이지,고객문의,고객문의처리 수정완료(#177)
  src/main/java/org/example/stockradar/feature/CustomerInquiry/controller/CustomerInquiryController.java
  src/main/java/org/example/stockradar/feature/auth/service/RedisSmtpService.java
  src/main/java/org/example/stockradar/feature/customerInquiryprocessing/controller/CustomerInquiryProcessingController.java
  src/main/java/org/example/stockradar/feature/customerInquiryprocessing/service/CustomerInquiryProcessingService.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
  src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
  src/main/java/org/example/stockradar/global/exception/ErrorCode.java
  src/main/resources/static/assets/js/customerInquiry/customerInquiry.js
  src/main/resources/static/assets/js/product/rxt4060Ti.js
Labels: refactor

#179 feat: 알림 2차 기능 구현 완료 (#164)
  build.gradle
  src/main/java/org/example/stockradar/StockradarApplication.java
  src/main/java/org/example/stockradar/config/JdaConfig.java
  src/main/java/org/example/stockradar/config/KafkaConsumerConfig.java
  src/main/java/org/example/stockradar/feature/auth/service/CoolsmsService.java
  src/main/java/org/example/stockradar/feature/auth/service/MemberService.java
  src/main/java/org/example/stockradar/feature/board/controller/BoardController.java
  src/main/java/org/example/stockradar/feature/board/controller/CommentController.java
  src/main/java/org/example/stockradar/feature/crawl/entity/StockStatus.java
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/feature/notification/controller/NotificationController.java
  src/main/java/org/example/stockradar/feature/notification/controller/ViewController.java
  src/main/java/org/example/stockradar/feature/notification/dto/NotificationEvent.java
  src/main/java/org/example/stockradar/feature/notification/dto/NotificationSettingsDto.java
  src/main/java/org/example/stockradar/feature/notification/entity/InterestProduct.java
  src/main/java/org/example/stockradar/feature/notification/entity/MemberNotification.java
  src/main/java/org/example/stockradar/feature/notification/entity/Notification.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationChannel.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationLog.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationSetting.java
  src/main/java/org/example/stockradar/feature/notification/entity/NotificationStatus.java
  src/main/java/org/example/stockradar/feature/notification/repository/InterestProductRepository.java
  src/main/java/org/example/stockradar/feature/notification/repository/MemberNotificationRepository.java
  src/main/java/org/example/stockradar/feature/notification/repository/NotificationSettingRepository.java
  src/main/java/org/example/stockradar/feature/notification/service/DiscordService.java
  src/main/java/org/example/stockradar/feature/notification/service/EmailService.java
  src/main/java/org/example/stockradar/feature/notification/service/InterestProductService.java
  src/main/java/org/example/stockradar/feature/notification/service/KafkaNotificationConsumer.java
  src/main/java/org/example/stockradar/feature/notification/service/KafkaNotificationProducer.java
  src/main/java/org/example/stockradar/feature/notification/service/NotificationDispatcherService.java
  src/main/java/org/example/stockradar/feature/notification/service/NotificationService.java
  src/main/java/org/example/stockradar/feature/notification/service/WebPushService.java
  src/main/resources/application.yml
  src/main/resources/static/assets/css/notification/toggle.css
  src/main/resources/static/assets/js/notification/readInterestProduct.js
  src/main/resources/templates/email-template/email-template.html
  src/main/resources/templates/notification/wishlist.html
Labels: feature

#184 refactor: 메인 배너 수정(#182)
  src/main/resources/templates/main.html
Labels: refactor

#185 Refactor/180
  src/main/java/org/example/stockradar/feature/notification/service/DiscordQueueService.java
  src/main/java/org/example/stockradar/feature/notification/service/DiscordService.java
  src/main/java/org/example/stockradar/feature/notification/service/EmailQueueService.java
  src/main/java/org/example/stockradar/feature/notification/service/EmailService.java
  src/main/java/org/example/stockradar/feature/notification/service/NotificationDispatcherService.java
  src/main/java/org/example/stockradar/feature/notification/service/NotificationService.java
  src/main/java/org/example/stockradar/feature/notification/service/SmsQueueService.java
  src/main/resources/application.yml
  src/main/resources/templates/notification/wishlist.html
Labels: refactor

#186 deploy: 추가 배포전 .yml 통일
  .github/workflows/cicd.yml
  BOOT-INF/classes/application-prod.yml
  build.gradle
  crawlingServer/__pycache__/crawler2.cpython-313.pyc
  crawlingServer/coroutine.py
  src/main/java/org/example/stockradar/config/ProductRedisConfig.java
  src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
  src/main/java/org/example/stockradar/global/exception/CustomException.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/templates/auth/signIn.html
  src/test/java/org/example/stockradar/CustomerInquiryProcessing/CustomerInquiryProcessingControllerAdminTest.java
  src/test/java/org/example/stockradar/CustomerInquiryProcessing/CustomerInquiryProcessingControllerTest.java
  src/test/java/org/example/stockradar/CustomerInquiryProcessing/CustomerInquiryProcessingServiceSelectTest.java
  src/test/java/org/example/stockradar/CustomerInquiryProcessing/CustomerInquiryProcessingServiceTest.java
  src/test/java/org/example/stockradar/StockradarApplicationTests.java
  src/test/java/org/example/stockradar/boardTest/BoardServiceTest.java
  src/test/java/org/example/stockradar/product/rxt3050/Rtx3050ControllerExceptionTest.java
  src/test/java/org/example/stockradar/view/CustomUserDetailsServiceTest.java
Labels: bugfix, approved, chore

#195 Refactor/193
  src/main/resources/static/assets/js/product/rxt3060Ti.js
  src/main/resources/static/assets/js/product/rxt4060Ti.js
  src/main/resources/templates/product/gpu/rtx3060Ti.html
  src/main/resources/templates/product/gpu/rtx4060Ti.html
Labels: refactor

#196 refactor: Main UI 수정 (#189)
  src/main/java/org/example/stockradar/feature/board/controller/BoardController.java
  src/main/java/org/example/stockradar/feature/notification/repository/NotificationRepository.java
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-1.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-2.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-3.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-4.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-5.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-1.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-2.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-3.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-4.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-5.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-6.jpg
  src/main/resources/static/assets/images/demoes/demo4/slider/slide-3.png
  src/main/resources/templates/layout.html
  src/main/resources/templates/main.html
Labels: refactor

#198 refactor: 메인 UI 2차 수정 (#197)
  src/main/resources/static/assets/images/main/banner_top_1.jpg
  src/main/resources/static/assets/images/main/banner_top_2.jpg
  src/main/resources/static/assets/images/main/banner_top_3.jpg
  src/main/resources/templates/layout.html
  src/main/resources/templates/main.html
Labels: refactor

#201 refactor: rayout.html 수정완료(#200)
  src/main/resources/templates/layout.html
Labels: refactor

#203 4차 메인 최신화
  src/main/java/org/example/stockradar/feature/board/controller/BoardController.java
  src/main/java/org/example/stockradar/feature/notification/repository/NotificationRepository.java
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-1.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-2.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-3.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-4.jpg
  src/main/resources/static/assets/images/demoes/demo4/banners/banner-5.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-1.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-2.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-3.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-4.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-5.jpg
  src/main/resources/static/assets/images/demoes/demo4/products/categories/category-6.jpg
  src/main/resources/static/assets/images/demoes/demo4/slider/slide-3.png
  src/main/resources/static/assets/images/main/CPU.jpg
  src/main/resources/static/assets/images/main/GPU.jpg
  src/main/resources/static/assets/images/main/SSD.jpg
  src/main/resources/static/assets/images/main/banner_top_1.jpg
  src/main/resources/static/assets/images/main/banner_top_2.jpg
  src/main/resources/static/assets/images/main/banner_top_3.jpg
  src/main/resources/static/assets/images/main/graphic.jpg
  src/main/resources/static/assets/images/main/mainboard.jpg
  src/main/resources/static/assets/js/product/rxt3060Ti.js
  src/main/resources/static/assets/js/product/rxt4060Ti.js
  src/main/resources/templates/board/form.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/main.html
  src/main/resources/templates/product/gpu/rtx3060Ti.html
  src/main/resources/templates/product/gpu/rtx4060Ti.html
Labels: maintenance, ui, approved
